apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cms-labs-capture.fullname" . }}-controller
  labels:
    {{- include "cms-labs-capture.labels" . | nindent 4 }}
automountServiceAccountToken: true
